target-version = "py38"

include = [
  "src/**/*.py"
]

[lint]
preview = true
extend-select = [
  "UP",  # pyupgrade
  "D",   # pydocstyle
  "PLW", # pylint warning
  "PLC", # pylint convention
  "PLR", # pylint refactor
]

[lint.pydocstyle]
convention = "pep257"
