name: Build package in standalone version
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: python -m pip install poetry

      - name: Install project
        working-directory: ${{ github.workspace }}
        run: poetry install

      - name: Use CLI as Python module
        run: python -m scipion-testrunner -h
