name: Build package within Scipion's enviroment
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}

      - name: Enable Pull Request Automerge
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --rebase --auto "${{ github.event.number }}"  

      - name: Install Miniconda  
        uses: conda-incubator/setup-miniconda@main
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: scipion3
          python-version: "3.8"

      - name: Install Scipion's dependencies    
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gcc-10 g++-10 make cmake
      
      - name: Install Scipion    
        working-directory: ${{ github.workspace }}/../
        run: |
          pip install --user scipion-installer
          python -m scipioninstaller -conda -noXmipp -noAsk scipion
    
      - name: Install project
        run: pip install -e .
      
      - name: Install dummy plugin for E2E testing
        working-directory: ${{ github.workspace }}/../scipion
        run: scipion3 installp -p ${{ github.workspace }}/tests/e2e/scipion-em-dummy --devel
      
      #- name: Run E2E test
      #  env:
      #    TEST_MODULE: dummy
      #  working-directory: ${{ github.workspace }}/../
      #  run: scipion_testrunner ./scipion/scipion3 $TEST_MODULE --noGpu --testData=${{ github.workspace }}/tests/e2e/scipion-em-$TEST_MODULE/$TEST_MODULE/testData.json
