name: Build package on Pull Request
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: python -m pip install poetry

      - name: Install project (standalone)
        working-directory: ${{ github.workspace }}
        run: poetry install

      - name: Install Scipion dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gcc-10 g++-10 make cmake

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@main
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: scipion3
          python-version: "3.8"

      - name: Install project (scipion env)
        run: pip install -e .
