name: Build package within Scipion's enviroment
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@main
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: scipion3
          python-version: "3.8"

      - name: Install Scipion's dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gcc-10 g++-10 make cmake
      
      - name: Install Scipion
        working-directory: ${{ github.workspace }}/../
        run: |
          pip install --user scipion-installer
          python -m scipioninstaller -conda -noXmipp -noAsk scipion

      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}

      - name: Install project
        run: pip install -e .
      
      - name: Run scipion-em tests
        working-directory: ${{ github.workspace }}/../
        run: |
          scipion-testrunner ./scipion/scipion3 pwem --noGpu
