name: Build package in standalone version
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}

      - name: Install project
        working-directory: ${{ github.workspace }}
        run: pip install -e .

      - name: Use CLI standalone
        run: ${{ vars.MODULE_NAME }} -h
      
      - name: Use CLI as Python module
        run: python -m ${{ vars.MODULE_NAME }} -h
      
      - name: Run unitary tests
        env:
          SCRIPT_PATH: ./scripts/run-tests.sh
        run: |
          chmod +x $SCRIPT_PATH
          python -m $SCRIPT_PATH
      
      - name: Check source code with Ruff
        run: python -m ruff check --config ./conf/ruff-src.toml
      
      - name: Check tests code with Ruff
        run: python -m ruff check --config ./conf/ruff-tests.toml
